Add casp3a and crab and crfbp
pharmacome/terminology pull request #15
Opened 2018-12-13 18:43 UTC by lingling93

2018-12-16 14:29 UTC, cthoyt commented
Need cross-references!

2018-12-16 15:09 UTC, lingling93 commented
Should I add it after merge ? @cthoyt

2018-12-16 15:10 UTC, cthoyt commented
Please add before merging

2019-01-13 19:00 UTC, cthoyt requested changes

2019-01-13 19:00 UTC, cthoyt commented on terms.tsv
> +HBP00324	Lingling	casp3a	protein	pmid:29807032	casp3a caspase 3, apoptosis-related cysteine peptidase a [ Danio rerio (zebrafish) ]
Needs cross references! Or just use entrez ID directly

2019-02-06 09:22 UTC, closed without merging